# Generated by Django 3.2 on 2024-03-13 08:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicInfo',
            fields=[
                ('id', models.BigAutoField(help_text='BasicInfo pk', primary_key=True, serialize=False)),
                ('sex', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)], verbose_name='성별')),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='연령')),
                ('edu_level', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='최종 학력')),
                ('edu_level_etc', models.TextField(blank=True, null=True, verbose_name='기타 최종 학력 입력 내용')),
                ('marital_status', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)], verbose_name='결혼 상태')),
                ('income_level', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='사회 경제 상태')),
                ('career_duration', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='경력 기간')),
                ('task_type', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)], verbose_name='업무 내용')),
                ('task_description', models.TextField(null=True, verbose_name='업무 내용 입력 문자열')),
                ('occupation_type', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='직업 형태')),
                ('interest', models.TextField(null=True, verbose_name='주요 관심 입력 문자열')),
            ],
        ),
        migrations.CreateModel(
            name='JobSatisfaction',
            fields=[
                ('id', models.BigAutoField(help_text='JobSatisfaction pk', primary_key=True, serialize=False)),
                ('satisfaction_level', models.FloatField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='업무 만족도')),
                ('participant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MentalCrowdWorkerProjectApp.basicinfo', verbose_name='BasicInfo pk')),
            ],
        ),
        migrations.CreateModel(
            name='StressFactors',
            fields=[
                ('id', models.BigAutoField(help_text='StressFactors pk', primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SleepHealth',
            fields=[
                ('id', models.BigAutoField(help_text='SleepHealth pk', primary_key=True, serialize=False)),
                ('result_1', models.TimeField(verbose_name='수면 시작 시각')),
                ('result_2', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1440)], verbose_name='수면 까지 걸리는 시간(분)')),
                ('result_3', models.TimeField(verbose_name='평소 기상 시각')),
                ('result_4', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1440)], verbose_name='실제 수면을 취한 시간(분)')),
                ('result_5a', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='5번 문항-a')),
                ('result_5b', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='5번 문항-b')),
                ('result_5c', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='5번 문항-c')),
                ('result_5d', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='5번 문항-d')),
                ('result_5e', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='5번 문항-e')),
                ('result_5f', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='5번 문항-f')),
                ('result_5g', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='5번 문항-g')),
                ('result_5h', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='5번 문항-h')),
                ('result_5i', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='5번 문항-i')),
                ('result_5j', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='5번 문항-j')),
                ('result_5j_input_text', models.TextField(null=True, verbose_name='입력된 기타 수면 장애 이유')),
                ('result_6', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='6번 문항')),
                ('result_7', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='7번 문항')),
                ('result_8', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='8번 문항')),
                ('result_9', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='9번 문항')),
                ('participant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MentalCrowdWorkerProjectApp.basicinfo', verbose_name='BasicInfo pk')),
            ],
        ),
        migrations.CreateModel(
            name='Loneliness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_1', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='1번 문항')),
                ('result_2', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='2번 문항')),
                ('result_3', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='3번 문항')),
                ('result_4', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='4번 문항')),
                ('result_5', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='5번 문항')),
                ('result_6', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='6번 문항')),
                ('participant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MentalCrowdWorkerProjectApp.basicinfo', verbose_name='BasicInfo pk')),
            ],
        ),
        migrations.CreateModel(
            name='JobSatisfactionStressFactors',
            fields=[
                ('id', models.BigAutoField(help_text='JobSatisfactionStressFactors pk', primary_key=True, serialize=False)),
                ('input_text', models.TextField(null=True, verbose_name='입력 문자열')),
                ('job_satisfaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_satisfaction_relations', to='MentalCrowdWorkerProjectApp.jobsatisfaction')),
                ('stress_factors', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='stress_factors_relations', to='MentalCrowdWorkerProjectApp.stressfactors')),
            ],
        ),
        migrations.AddField(
            model_name='jobsatisfaction',
            name='stress_factors',
            field=models.ManyToManyField(related_name='exercise_type', through='MentalCrowdWorkerProjectApp.JobSatisfactionStressFactors', to='MentalCrowdWorkerProjectApp.StressFactors'),
        ),
        migrations.CreateModel(
            name='GeneralHealth',
            fields=[
                ('id', models.BigAutoField(help_text='GeneralHealth pk', primary_key=True, serialize=False)),
                ('result_1', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='1번 문항')),
                ('result_2', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='2번 문항')),
                ('result_3', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='3번 문항')),
                ('result_4', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='4번 문항')),
                ('result_5', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='5번 문항')),
                ('result_6', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='6번 문항')),
                ('result_7', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='7번 문항')),
                ('result_8', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='8번 문항')),
                ('result_9', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='9번 문항')),
                ('result_10', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='10번 문항')),
                ('result_11', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='11번 문항')),
                ('result_12', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='12번 문항')),
                ('result_13', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)], verbose_name='13번 문항')),
                ('result_14', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)], verbose_name='14번 문항')),
                ('result_15', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)], verbose_name='15번 문항')),
                ('participant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MentalCrowdWorkerProjectApp.basicinfo', verbose_name='BasicInfo pk')),
            ],
        ),
        migrations.CreateModel(
            name='Emotion',
            fields=[
                ('id', models.BigAutoField(help_text='Emotion pk', primary_key=True, serialize=False)),
                ('result_1', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='1번 문항')),
                ('result_2', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='2번 문항')),
                ('result_3', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='3번 문항')),
                ('result_4', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='4번 문항')),
                ('result_5', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='5번 문항')),
                ('result_6', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='6번 문항')),
                ('result_7', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='7번 문항')),
                ('result_8', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='8번 문항')),
                ('result_9', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='9번 문항')),
                ('result_10', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='10번 문항')),
                ('result_11', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='11번 문항')),
                ('result_12', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='12번 문항')),
                ('result_13', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='13번 문항')),
                ('result_14', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='14번 문항')),
                ('result_15', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='15번 문항')),
                ('result_16', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='16번 문항')),
                ('result_17', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='17번 문항')),
                ('result_18', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='18번 문항')),
                ('result_19', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='19번 문항')),
                ('result_20', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='20번 문항')),
                ('result_21', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='21번 문항')),
                ('participant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MentalCrowdWorkerProjectApp.basicinfo', verbose_name='BasicInfo pk')),
            ],
        ),
    ]
