# Generated by Django 3.2 on 2024-03-17 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MentalCrowdWorkerProjectApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotion',
            name='participant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emotion_set', to='MentalCrowdWorkerProjectApp.basicinfo', verbose_name='BasicInfo pk'),
        ),
        migrations.AlterField(
            model_name='generalhealth',
            name='participant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='general_health_set', to='MentalCrowdWorkerProjectApp.basicinfo', verbose_name='BasicInfo pk'),
        ),
        migrations.AlterField(
            model_name='jobsatisfaction',
            name='participant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_satisfaction_set', to='MentalCrowdWorkerProjectApp.basicinfo', verbose_name='BasicInfo pk'),
        ),
        migrations.AlterField(
            model_name='jobsatisfaction',
            name='stress_factors',
            field=models.ManyToManyField(through='MentalCrowdWorkerProjectApp.JobSatisfactionStressFactors', to='MentalCrowdWorkerProjectApp.StressFactors'),
        ),
        migrations.AlterField(
            model_name='jobsatisfactionstressfactors',
            name='job_satisfaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_satisfaction_stress_factors_set', to='MentalCrowdWorkerProjectApp.jobsatisfaction'),
        ),
        migrations.AlterField(
            model_name='jobsatisfactionstressfactors',
            name='stress_factors',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='job_satisfaction_stress_factors_set', to='MentalCrowdWorkerProjectApp.stressfactors'),
        ),
        migrations.AlterField(
            model_name='loneliness',
            name='participant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loneliness_set', to='MentalCrowdWorkerProjectApp.basicinfo', verbose_name='BasicInfo pk'),
        ),
        migrations.AlterField(
            model_name='sleephealth',
            name='participant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sleep_health_set', to='MentalCrowdWorkerProjectApp.basicinfo', verbose_name='BasicInfo pk'),
        ),
    ]
