# Generated by Django 3.2 on 2025-07-04 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MentalCrowdWorkerProjectApp', '0002_auto_20240318_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicinfo',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='사용자 이름'),
        ),
    ]
